// Auth Actions
export const SET_USER = 'SET_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';

// User/Company Registration
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED";
export const USER_REGISTRATION_DEFAULT = "USER_REGISTRATION_DEFAULT";
export const USER_REGISTRATION_PROGRESS = "USER_REGISTRATION_PROGRESS";
export const COMPANY_LOGO_UPLOAD_SUCCESS = "COMPANY_LOGO_UPLOAD_SUCCESS";
export const COMPANY_LOGO_UPLOAD_FAILED = "COMPANY_LOGO_UPLOAD_FAILED";
export const USER_REGISTRATION_COMPLETED = "USER_REGISTRATION_COMPLETED";

// Profile Updates
export const COMPANY_PROFILE_UPDATE_DEFAULT = "COMPANY_PROFILE_UPDATE_DEFAULT";
export const COMPANY_PROFILE_UPDATE_SUCCESS = "COMPANY_PROFILE_UPDATE_SUCCESS";
export const COMPANY_PROFILE_UPDATE_FAILED = "COMPANY_PROFILE_UPDATE_FAILED";

// Quiz Actions
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILED = "CREATE_QUIZ_FAILED";
export const CREATE_QUIZ_DEFAULT = "CREATE_QUIZ_DEFAULT";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_FAILED = "UPDATE_QUIZ_FAILED";

// Job Actions
export const POST_JOB_SUCCESS = "POST_JOB_SUCCESS";
export const POST_JOB_FAILED = "POST_JOB_FAILED";
export const POST_JOB_DEFAULT = "POST_JOB_DEFAULT";

// Table Actions
export const QUIZ_TABLE = "QUIZ_TABLE";
export const JOB_TABLE = "JOB_TABLE";
export const PAYMENT_HISTORY_TABLE = "PAYMENT_HISTORY_TABLE";
export const APPLICANTS_TABLE = "APPLICANTS_TABLE";

// Menu Actions
export const MENU_OPEN = "MENU_OPEN";
export const MENU_CLOSE = "MENU_CLOSE";
export const MENU_DEFAULT = "MENU_DEFAULT";

// stats
export const TOTAL_JOBS = "TOTAL_JOBS";
export const ACTIVE_WORKERS = "ACTIVE_WORKERS";
export const OPEN_JOBS = "OPENED_JOBS";
export const CLOSED_JOBS = "CLOSED_JOBS";

// Other
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const UNSUBSCRIBED = "UNSUBSCRIBED";
